// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

package com.tryingpfq.grpc;

public interface AddReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mygrpc.AddReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 res = 1;</code>
   * @return The res.
   */
  int getRes();
}
